{
 "title": "Litterbox",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raw 4 sensors",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w0\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))"
    },
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))"
    },
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))"
    },
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))"
    }
   ]
  },
  {
   "title": "Total system weight and state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w-sum\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))"
    },
    {
     "query": "import \"join\"\n\nleft = from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\n\nright = from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\n  |> last()\n  |> map(fn: (r) => ({r with _time: v.timeRangeStop}))\n\nunion(tables: [left, right])\n"
    },
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"debug\")"
    }
   ]
  },
  {
   "title": "Cat weight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "import \"join\"\n\nleft = from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w-cat\")\n  |> map(fn: (r) => ({r with _value: r._value / 10}))\n\nright = from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w-cat\")\n  |> map(fn: (r) => ({r with _value: r._value / 10}))\n  |> last()\n  |> map(fn: (r) => ({r with _time: now()}))\n\nunion(tables: [left, right])"
    }
   ]
  },
  {
   "title": "Poo weight (last five)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w-poo\")\n  |> map(fn: (r) => ({r with _value: r._value / 10}))\n  |> bottom(n: 5)"
    }
   ]
  },
  {
   "title": "Poo count by day of the week",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 14 },
   "targets": [
    {
     "query": "import \"join\"\n\nnonZeroCount = from(bucket: \"sensorRawLog\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poo-count\")\n  |> window(every: 1d)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> count()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n\nzeros = from(bucket: \"sensorRawLog\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poo-count\")\n  |> window(every: 1d)\n  |> sum()\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n\nunion(tables: [nonZeroCount, zeros])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Poo count (right now)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poo-count\")"
    }
   ]
  },
  {
   "title": "Total system weight and reset reason",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"w-sum\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))"
    },
    {
     "query": "import \"join\"\n\nleft = from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rst-reason\")\n\nright = from(bucket: \"sensorRawLog\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rst-reason\")\n  |> last()\n  |> map(fn: (r) => ({r with _time: v.timeRangeStop}))\n\nunion(tables: [left, right])\n"
    },
    {
     "query": "from(bucket: \"sensorRawLog\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"debug\")"
    }
   ]
  }
 ]
}